// Generated by LiveScript 1.6.0
(function(){
  var nav_menu, nav_collection;
  nav_menu = document.getElementById("nav_menu");
  nav_collection = document.getElementById("nav_collection");
  nav_menu.onclick = function(){
    return nav_collection.classList.toggle("visible");
  };
}).call(this);
